In [120]:
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')

In [121]:
columns=['questions','recharge_type']
data = pd.read_csv('./questions.txt',sep='|',names=columns)

In [122]:
#data['questions']

In [123]:
def shuffle(df, n=1, axis=0):
    df = df.copy()
    for _ in range(n):
        df.apply(np.random.shuffle,axis=axis)
    return df

In [124]:
data = data.reindex(np.random.permutation(data.index))

In [125]:
#data

In [126]:
X_train = data['questions'][:50].as_matrix()
y_train = data['recharge_type'][:50].as_matrix()
X_test = data['questions'][50:].as_matrix()
y_test = data['recharge_type'][50:].as_matrix()

In [127]:
#X_train,y_train

In [128]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

In [129]:
#text_clf = Pipeline([('vect',CountVectorizer()),('tfidf',TfidfTransformer()),('clf',MultinomialNB())])

In [130]:
#text_clf = text_clf.fit(X_train,y_train)

In [131]:
#predicted = text_clf.predict(X_test)
#np.mean(predicted == y_test)

In [132]:
from sklearn.linear_model import SGDClassifier
new_text_clf = Pipeline([('vect',CountVectorizer()),('tfidf',TfidfTransformer()),('clf',SGDClassifier(loss='hinge',penalty='l2',alpha=1e-2,n_iter=5,random_state=42))])

In [133]:
new_text_clf.fit(X_train,y_train)

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...     penalty='l2', power_t=0.5, random_state=42, shuffle=True, verbose=0,
       warm_start=False))])

In [134]:
new_predicted = new_text_clf.predict(X_test)
np.mean(new_predicted == y_test)

0.92307692307692313

In [135]:
from sklearn import metrics
#print(metrics.classification_report(y_test, new_predicted,target_names=['0','1]))

In [136]:
metrics.confusion_matrix(new_predicted,y_test)

array([[19,  1],
       [ 1,  5]])

In [137]:
new_text_clf.predict(["reacharge my phone with rs 250 in airtel"])

array([1])

In [138]:
from sklearn.externals import joblib

In [139]:
joblib.dump(new_text_clf,'naive_classifier_model.pkl')

['naive_classifier_model.pkl',
 'naive_classifier_model.pkl_01.npy',
 'naive_classifier_model.pkl_02.npy',
 'naive_classifier_model.pkl_03.npy',
 'naive_classifier_model.pkl_04.npy',
 'naive_classifier_model.pkl_05.npy',
 'naive_classifier_model.pkl_06.npy']

In [140]:
okay = joblib.load('naive_classifier_model.pkl')

In [141]:
okay.predict(["How are you?"])

array([0])